#!/bin/bash

# Check if the first 3 arguments are provided
if [ -z $1 ] || [ -z $2 ] || [ -z $3 ]; then
    echo "Error: The first 3 arguments are mandatory."
    echo "Usage: ./contribute <Study-Name> <Full-Path-To-Study> <Author-Name> <Branch-Name> <PR-title> <PR-Body>"
    exit 1
fi

# Set the last 3 arguments to "#" if not provided
arg4=$4
arg5=$5
arg6=$6
if [ -z $4 ]; then
arg4="#"
fi
if [ -z $5 ]; then
arg5="#"
fi
if [ -z $6 ]; then
arg6="#"
fi
python3 contribute.py "$1" "$2" "$3" "$arg4" "$arg5" "$arg6"
