#!/bin/bash
which open
if [ $? == 0 ] 
then
   if [[ "$OSTYPE" =~ ^darwin ]]; then
      open -a 'Google Chrome' https://controlcore-project.github.io/concore-editor/
   elif [[ "$OSTYPE" =~ ^linux ]]; then
      xdg-open https://controlcore-project.github.io/concore-editor/
   fi
else
   which xdg-open
   if [ $? == 0 ] 
   then
      xdg-open https://controlcore-project.github.io/concore-editor/
   else
      echo "unable to open browser for the concore editor."
   fi
fi
