#!/bin/bash
if [ $# == 0 ]
then
    echo "Make a concore study "
    echo "  ./makestudy path/name.graphml"
    echo "  ./makestudy path/name.graphml study"
    echo "In the first case, the name of the study is the same as the name of the .graphml"
    echo "In either case, source files come from the same path as the .graphml"
    echo "The equivalent mkconcore.py is displayed"
    exit
fi
graphml=$1
if [ -e $graphml ]
then
    sourcedir=$(dirname "$graphml")
else
    graphml=$graphml'.graphml'
    if [ -e $graphml ]
    then
        sourcedir=$(dirname "$graphml")
    else
        echo "$graphml does not exist"
        exit
    fi
fi
if [ $# = 1 ]
then
    studydir=`basename ${graphml%\.*}`
else
    studydir=$2
fi
if [ -e $studydir ]
then
    echo "cannot make $studydir because one already exists with that name"
    echo "either do ./destroy $studydir, or choose a unique name as 2nd arg"
else
    which osascript >/dev/null
    if [ $? == 0 ] 
    then
       echo "python3 mkconcore.py $graphml $sourcedir $studydir macos"
       python3 mkconcore.py $graphml $sourcedir $studydir macos
    else
       echo "python3 mkconcore.py $graphml $sourcedir $studydir ubuntu"
       python3 mkconcore.py $graphml $sourcedir $studydir ubuntu
    fi
fi
